In [1]:
import pandas as pd
import spacy
import sys
sys.path.insert(0, r'C:\Users\eduardo.moreno\OneDrive - NEORIS\Desktop\courses\nlp\nlp_nanook\src') # Windows
from utils.utils import clean_text

In [2]:
df_stemm_lemm = pd.read_pickle(r'..\..\..\data\preprocessed\stemm_lemm_stop_words_stop.pkl')

In [3]:
df_stemm_lemm.columns

Index(['Facebook Id', 'Post Created', 'Total Interactions', 'Likes',
       'Comments', 'Shares', 'Love', 'Wow', 'Haha', 'Sad', 'Angry', 'Care',
       'Message', 'Message_stpWrd', 'Message_clean_stpWrd',
       'Message_clean_stemm_stpWrd', 'Message_clean_lemm_stpWrd'],
      dtype='object')

In [4]:
df_stemm_lemm.head()

,Facebook Id,Post Created,Total Interactions,Likes,Comments,Shares,Love,Wow,Haha,Sad,Angry,Care,Message,Message_stpWrd,Message_clean_stpWrd,Message_clean_stemm_stpWrd,Message_clean_lemm_stpWrd
0,153630631414604,2016-01-05 20:55:17 CST,"7,836",7266,442,63,51,1,9,2,0,2,A LOS NACIDOS ENTRE 1970 Y 1987 Somos una gene...,NACIDOS 1970 1987 generación especial denomina...,nacidos 1970 1987 generacion especial denomina...,nac 1970 1987 som gener especial denomin gener...,nacido 1970 1987 generacion especial denominar...
1,344760762323803,2018-03-25 20:22:33 CST,"12,530",2946,44,9025,357,4,112,7,17,18,PORQUE VOTARE POR GUSTAVO PETRO Hoy quiero com...,VOTARE GUSTAVO PETRO quiero compartir ustedes ...,votare gustavo petro quiero compartir ustedes ...,porqu votar gustav petr quier compart seguidor...,votare gustavo petro querer compartir seguidor...
2,663135523805166,2018-04-26 15:23:31 CDT,"3,727",2137,77,917,583,10,2,0,1,0,"Ministra de medio ambiente, a trabajar por el ...","Ministra medio ambiente, cambio climático desc...",ministra medio ambiente cambio climatico desca...,ministr medi ambient trabaj cambi climat desca...,ministra medio ambiente cambio climatico desca...
3,461295120574213,2016-05-02 17:59:04 CDT,"3,146",2548,249,188,123,7,28,2,1,0,A LOS NACIDOS ENTRE 1970 Y 1987 Somos una gene...,NACIDOS 1970 1987 generación especial denomina...,nacidos 1970 1987 generacion especial denomina...,nac 1970 1987 som gener especial denomin gener...,nacido 1970 1987 generacion especial denominar...
4,663135523805166,2016-06-28 23:41:26 CDT,"2,804",2367,57,181,87,5,3,8,96,0,AYÚDANOS A COMPARTIR LA IMAGEN.. Por tan magni...,AYÚDANOS COMPARTIR IMAGEN.. magnicfico POT (Pl...,ayudanos compartir imagen magnicfico pot plan ...,ayudan compart imag magnicf pot plan orden ter...,ayudano compartir imagen magnicfico pot plan o...

In [5]:
nlp = spacy.load('es_core_news_lg')

In [6]:
def lematizar_texto(texto):
    lemas = nlp(texto)
    lematizado = [token.lemma_ for token in lemas]
    return ' '.join(lematizado)

In [7]:
df_stemm_lemm['Message_clean_lemm_stpWrd'][5]

'carino chileno mas verano chile especial santiago estación aca marcar santiago verano calor invierno frio costar frio consejo preparado mentalizado tendrar ropa invierno aca pasar invierno pronto llegar patronato recoleta encontrar ropa invierno precio conveniente tambien estacion central invierno mas costoso verano nevar valle santiago mas 10 ano realidad recordar santiago encuetrar valle rodeado cordillera andes costa soler nevar cordillera postal clasico santiago cordillera nevado fondo creer cambio climatico mas comun nieve ciudad chileno aparte frio invierno uds tendran frio alma lejos tierra sentirar mas frio pais aun existir tirania oprimir pueblo venezolano sentir frio persona hambre nino chileno aun lograr entender gobernar venezuela bocado boca hambre sed libertad pueblo lograr entender maldad tirania destruir hermoso nacion gente bello hermoso sentimiento virtud chileno tambien conviccion pleno pesadilla atormentar venezuela caer caer duro pagar dano favor rindas vida puedas respirar aun luchar perder esperanza sepas chile apoyar pronto volveran sonreir fuerte latinoamerico escuchar chileno sonreiremo hermano venezolano aca celebrarer dia soltarar mano deseo venezolano mundo querer vida sonriar fortaleza decision tomar abrazo apretado carino uds recuerden frase aca llegar pronto vera querer chile amigo forastero 3 imagen santiago 15 julio 2017'

In [8]:
lematizar_texto("estaciones")

'estación'

In [9]:
print(f"Lemmatized message: \n{df_stemm_lemm['Message_clean_lemm_stpWrd'][5]}\n")
print(f"Lemmatized + clean message: \n{clean_text(df_stemm_lemm['Message_clean_lemm_stpWrd'][5])}")

Lemmatized message:
carino chileno mas verano chile especial santiago estación aca marcar santiago verano calor invierno frio costar frio consejo preparado mentalizado tendrar ropa invierno aca pasar invierno pronto llegar patronato recoleta encontrar ropa invierno precio conveniente tambien estacion central invierno mas costoso verano nevar valle santiago mas 10 ano realidad recordar santiago encuetrar valle rodeado cordillera andes costa soler nevar cordillera postal clasico santiago cordillera nevado fondo creer cambio climatico mas comun nieve ciudad chileno aparte frio invierno uds tendran frio alma lejos tierra sentirar mas frio pais aun existir tirania oprimir pueblo venezolano sentir frio persona hambre nino chileno aun lograr entender gobernar venezuela bocado boca hambre sed libertad pueblo lograr entender maldad tirania destruir hermoso nacion gente bello hermoso sentimiento virtud chileno tambien conviccion pleno pesadilla atormentar venezuela caer caer duro pagar dano favor rindas vida puedas respirar aun luchar perder esperanza sepas chile apoyar pronto volveran sonreir fuerte latinoamerico escuchar chileno sonreiremo hermano venezolano aca celebrarer dia soltarar mano deseo venezolano mundo querer vida sonriar fortaleza decision tomar abrazo apretado carino uds recuerden frase aca llegar pronto vera querer chile amigo forastero 3 imagen santiago 15 julio 2017

Lemmatized + clean message:
carino chileno mas verano chile especial santiago estacion aca marcar santiago verano calor invierno frio costar frio consejo preparado mentalizado tendrar ropa invierno aca pasar invierno pronto llegar patronato recoleta encontrar ropa invierno precio conveniente tambien estacion central invierno mas costoso verano nevar valle santiago mas 10 ano realidad recordar santiago encuetrar valle rodeado cordillera andes costa soler nevar cordillera postal clasico santiago cordillera nevado fondo creer cambio climatico mas comun nieve ciudad chileno aparte frio invierno uds tendran frio alma lejos tierra sentirar mas frio pais aun existir tirania oprimir pueblo venezolano sentir frio persona hambre nino chileno aun lograr entender gobernar venezuela bocado boca hambre sed libertad pueblo lograr entender maldad tirania destruir hermoso nacion gente bello hermoso sentimiento virtud chileno tambien conviccion pleno pesadilla atormentar venezuela caer caer duro pagar dano favor rindas vida puedas respirar aun luchar perder esperanza sepas chile apoyar pronto volveran sonreir fuerte latinoamerico escuchar chileno sonreiremo hermano venezolano aca celebrarer dia soltarar mano deseo venezolano mundo querer vida sonriar fortaleza decision tomar abrazo apretado carino uds recuerden frase aca llegar pronto vera querer chile amigo forastero 3 imagen santiago 15 julio 2017

In [10]:
clean_lemm = df_stemm_lemm['Message_clean_lemm_stpWrd'].apply(lambda x: clean_text(x))
df_stemm_lemm['Message_clean_lemm_stpWrd'] = clean_lemm

In [11]:
df_stemm_lemm.head()

,Facebook Id,Post Created,Total Interactions,Likes,Comments,Shares,Love,Wow,Haha,Sad,Angry,Care,Message,Message_stpWrd,Message_clean_stpWrd,Message_clean_stemm_stpWrd,Message_clean_lemm_stpWrd
0,153630631414604,2016-01-05 20:55:17 CST,"7,836",7266,442,63,51,1,9,2,0,2,A LOS NACIDOS ENTRE 1970 Y 1987 Somos una gene...,NACIDOS 1970 1987 generación especial denomina...,nacidos 1970 1987 generacion especial denomina...,nac 1970 1987 som gener especial denomin gener...,nacido 1970 1987 generacion especial denominar...
1,344760762323803,2018-03-25 20:22:33 CST,"12,530",2946,44,9025,357,4,112,7,17,18,PORQUE VOTARE POR GUSTAVO PETRO Hoy quiero com...,VOTARE GUSTAVO PETRO quiero compartir ustedes ...,votare gustavo petro quiero compartir ustedes ...,porqu votar gustav petr quier compart seguidor...,votare gustavo petro querer compartir seguidor...
2,663135523805166,2018-04-26 15:23:31 CDT,"3,727",2137,77,917,583,10,2,0,1,0,"Ministra de medio ambiente, a trabajar por el ...","Ministra medio ambiente, cambio climático desc...",ministra medio ambiente cambio climatico desca...,ministr medi ambient trabaj cambi climat desca...,ministra medio ambiente cambio climatico desca...
3,461295120574213,2016-05-02 17:59:04 CDT,"3,146",2548,249,188,123,7,28,2,1,0,A LOS NACIDOS ENTRE 1970 Y 1987 Somos una gene...,NACIDOS 1970 1987 generación especial denomina...,nacidos 1970 1987 generacion especial denomina...,nac 1970 1987 som gener especial denomin gener...,nacido 1970 1987 generacion especial denominar...
4,663135523805166,2016-06-28 23:41:26 CDT,"2,804",2367,57,181,87,5,3,8,96,0,AYÚDANOS A COMPARTIR LA IMAGEN.. Por tan magni...,AYÚDANOS COMPARTIR IMAGEN.. magnicfico POT (Pl...,ayudanos compartir imagen magnicfico pot plan ...,ayudan compart imag magnicf pot plan orden ter...,ayudano compartir imagen magnicfico pot plan o...

Eliminar mensajes duplicados

In [12]:
df_stemm_lemm.shape

(1392634, 17)

In [13]:
df_stemm_lemm.drop_duplicates(subset="Message_clean_lemm_stpWrd").shape

(1097515, 17)

Hay un total de $295,119$ repetidos, lo cual puede interpretare como "reposts" de otro mensaje.

In [14]:
df_stemm_lemm.to_pickle(r'..\..\..\data\preprocessed\clean_stemm_lemm_stop_words.pkl')

In [15]:
df_stemm_lemm.drop_duplicates(subset="Message_clean_lemm_stpWrd").to_pickle(r'..\..\..\data\preprocessed\clean_stemm_lemm_stop_words_uniques.pkl')