# Load data

In [1]:
import pandas as pd

In [ ]:
df = pd.read_pickle(r"../../../data/preprocessed/stemm_lemm_stop_words_stop_fb_pages_2016.pkl")

In [3]:
df.shape

(62844, 17)

In [4]:
df.head()

,Facebook Id,Post Created,Total Interactions,Likes,Comments,Shares,Love,Wow,Haha,Sad,Angry,Care,Message,Message_stpWrd,Message_clean_stpWrd,Message_clean_stemm_stpWrd,Message_clean_lemm_stpWrd
0,129348553750248,2016-12-31 23:56:34 CST,17,13,0,4,0,0,0,0,0,0,"FELIZ AÑO NUEVO! Belice, Costa Rica, El Salvad...","FELIZ AÑO NUEVO! Belice, Costa Rica, Salvador,...",feliz ano belice costa rica salvador guatemala...,feliz ano nuev belic cost ric salvador guatema...,feliz ano belice costa rico salvador guatemala...
1,129348553750248,2016-12-31 23:50:53 CST,2,2,0,0,0,0,0,0,0,0,MENSAJE DE PRESERVE PLANET PARA EL NUEVO AÑO. ...,"MENSAJE PRESERVE PLANET AÑO. 📃 Iniciamos 2017,...",mensaje preserve planet ano iniciamos 2017 med...,mensaj preserv planet par nuev ano inici 2017 ...,mensaje preserve planet ano iniciar 2017 medio...
2,100067845290450,2016-12-31 23:13:19 CST,19,15,0,3,1,0,0,0,0,0,Un #FelizAño les desea el Instituto Distrital ...,#FelizAño desea Instituto Distrital Gestión Ri...,felizano desea instituto distrital gestion rie...,felizan dese institut distrital gestion riesg ...,felizano desear instituto distrital gestion ri...
3,100070452191560,2016-12-31 22:40:00 CST,5,3,0,2,0,0,0,0,0,0,"Francia busca siempre ""con el diálogo solucion...","Francia busca ""con diálogo soluciones"", Oriente",francia busca dialogo soluciones tambien oriente,franci busc siempr dialog solucion tambi orient,francia buscar dialogo solución tambien oriente
4,129348553750248,2016-12-31 22:31:54 CST,6,5,0,0,1,0,0,0,0,0,FELIZ AÑO NUEVO! ⤵️ MENSAJE DE PRESERVE PLANET...,FELIZ AÑO NUEVO! ⤵️ MENSAJE PRESERVE PLANET 20...,feliz ano mensaje preserve planet 2017 iniciam...,feliz ano nuev mensaj preserv planet par 2017 ...,feliz ano mensaje preserve planet 2017 iniciar...

In [5]:
df.columns

Index(['Facebook Id', 'Post Created', 'Total Interactions', 'Likes',
       'Comments', 'Shares', 'Love', 'Wow', 'Haha', 'Sad', 'Angry', 'Care',
       'Message', 'Message_stpWrd', 'Message_clean_stpWrd',
       'Message_clean_stemm_stpWrd', 'Message_clean_lemm_stpWrd'],
      dtype='object')

In [6]:
selected_data = df[['Message' ,'Message_stpWrd', 'Message_clean_lemm_stpWrd']]

In [7]:
selected_data.head()

,Message,Message_stpWrd,Message_clean_lemm_stpWrd
0,"FELIZ AÑO NUEVO! Belice, Costa Rica, El Salvad...","FELIZ AÑO NUEVO! Belice, Costa Rica, Salvador,...",feliz ano belice costa rico salvador guatemala...
1,MENSAJE DE PRESERVE PLANET PARA EL NUEVO AÑO. ...,"MENSAJE PRESERVE PLANET AÑO. 📃 Iniciamos 2017,...",mensaje preserve planet ano iniciar 2017 medio...
2,Un #FelizAño les desea el Instituto Distrital ...,#FelizAño desea Instituto Distrital Gestión Ri...,felizano desear instituto distrital gestion ri...
3,"Francia busca siempre ""con el diálogo solucion...","Francia busca ""con diálogo soluciones"", Oriente",francia buscar dialogo solución tambien oriente
4,FELIZ AÑO NUEVO! ⤵️ MENSAJE DE PRESERVE PLANET...,FELIZ AÑO NUEVO! ⤵️ MENSAJE PRESERVE PLANET 20...,feliz ano mensaje preserve planet 2017 iniciar...

# spaCy

We are going to use `spaCy`'s pretrained models to extract all organizations mentioned on the posts

In [8]:
import spacy
from spacy import displacy
from collections import Counter

In [9]:
spacy.__version__

'3.7.4'

In [10]:
nlp = spacy.load('es_core_news_lg')

We will use `spaCy` models to identify and extract organizations from posts:

In [11]:
doc = nlp(selected_data.iloc[4183]['Message'])

In [12]:
#displacy.serve(doc, style="ent", auto_select_port=True)

In [13]:
doc.ents

(BOLIVIA,
 Bolivia,
 Ciudad de la Paz,
 Sistema Capitalista,
 Altiplano,
 Bolivia,
 EPSAS,
 Los denominados megaproyectos extractivos,
 Las hidroeléctricas que se quiere construir en la selva del Norte de Bolivia,
 Brasil,
 El agronegocio tan fomentado por el gobierno,
 Cambio Climático,
 El agronegocio también significó que,
 3.147.229.-,
 Bolivia,
 Has,
 Vice.,
 Lic. Linera,
 Has,
 Todas esta políticas que siguen,
 MAS,
 Movimientos Sociales,
 El pueblo,
 Romina)

Generar función para extraer todas las organizaciones mencionadas en cada un post de Facebook.

In [14]:
def get_orgs(text):
    doc = nlp(text)
    org_list = []
    for entity in doc.ents:
        if entity.label_ == 'ORG':
            org_list.append(entity.text)
    org_list = list(set(org_list))
    return org_list

The next cell takes around $4$ hours to extract all organizations...

In [15]:
if 1 == 0:
    selected_data['organizations'] = selected_data['Message'].apply(get_orgs)
    selected_data.to_pickle(r"../../../data/preprocessed/full_data_organizations_2016.pkl")
else:
    selected_data = pd.read_pickle(r"../../../data/preprocessed/full_data_organizations_2016.pkl")
selected_data.head()

,Message,Message_stpWrd,Message_clean_lemm_stpWrd,organizations
0,"FELIZ AÑO NUEVO! Belice, Costa Rica, El Salvad...","FELIZ AÑO NUEVO! Belice, Costa Rica, Salvador,...",feliz ano belice costa rico salvador guatemala...,"[📃 Iniciamos 2017, Comisión Interinstitucional..."
1,MENSAJE DE PRESERVE PLANET PARA EL NUEVO AÑO. ...,"MENSAJE PRESERVE PLANET AÑO. 📃 Iniciamos 2017,...",mensaje preserve planet ano iniciar 2017 medio...,"[📃 Iniciamos 2017, Comisión Interinstitucional..."
2,Un #FelizAño les desea el Instituto Distrital ...,#FelizAño desea Instituto Distrital Gestión Ri...,felizano desear instituto distrital gestion ri...,[Cambio Climático - Idiger #]
3,"Francia busca siempre ""con el diálogo solucion...","Francia busca ""con diálogo soluciones"", Oriente",francia buscar dialogo solución tambien oriente,[]
4,FELIZ AÑO NUEVO! ⤵️ MENSAJE DE PRESERVE PLANET...,FELIZ AÑO NUEVO! ⤵️ MENSAJE PRESERVE PLANET 20...,feliz ano mensaje preserve planet 2017 iniciar...,"[📃 Iniciamos 2017, Comisión Interinstitucional..."

Let's extract all organizations:

In [16]:
orgs = selected_data['organizations'].to_list()
orgs = [org for sublist in orgs for org in sublist]

In [17]:
org_freq = Counter(orgs)
org_freq.most_common(20)

[('Cambio Climático', 2952),
 ('ONU', 1363),
 ('Acuerdo de París', 822),
 ('Naciones Unidas', 716),
 ('FAO', 504),
 ('WWF', 476),
 ('NASA', 456),
 ('Unión Europea', 344),
 ('Gobierno', 326),
 ('COP22', 265),
 ('Congreso', 247),
 ('Objetivos de Desarrollo Sostenible', 235),
 ('UE', 234),
 ('PNUD', 200),
 ('UNAM', 170),
 ('National Geographic', 165),
 ('Greenpeace', 159),
 ('PNUMA', 144),
 ('AcuerdoDeParís', 140),
 ('CambioClimático', 139)]

What about the following post?

In [18]:
print(selected_data.iloc[0]['Message'])

FELIZ AÑO NUEVO! Belice, Costa Rica, El Salvador, Guatemala, Honduras, México, Nicaragua. ⤵️ MENSAJE DE PRESERVE PLANET PARA EL 2017 📃 Iniciamos 2017, en medio de grandes retos pues una gran parte de la población humana, aun ignora o trata de ignorar los grandes problemas que enfrenta el Planeta, el único donde podemos vivir. El inicio de un año es siempre buen momento para corregir defectos o fomentar cualidades. Desde PRESERVE PLANET nos gustaría escuchar que entre los típicos propósitos que se hace la gente, también estuviera el de "disminuir y abandonar el consumo de plástico desechable", "no comprar animales silvestres", “Iniciaré el año abandonando el consumo de carne y mariscos”, "no usar productos probados en animales", “Ser menos consumista” en fin, la aplicación de los consejos que constantemente publicamos, los cuales hemos denominado, “El Poder de Uno”. Pero todavía no hemos logrado que estos temas sean motivo de inquietud, interés o urgencia para la mayoría de la sociedad. Nos falta un largo camino por recorrer aún. El respeto a todas las formas de vida o el reconocimiento de los derechos de los animales no habrán de darse en los próximos años, pero ahora estamos sentando los precedentes para lo que ya está siendo, el movimiento social más importante de este milenio. Cada vez más personas se manifiestan en contra de la destrucción de la naturaleza, en contra del uso y maltrato de los animales no humanos en todos los ámbitos de nuestra vida cotidiana. Las legislaciones avanzan lentamente, pero están avanzando. Nuestros pasos a favor del ambiente, son lentos en comparación con la velocidad con que se da la destrucción ambiental y la matanza de especies. Es normal sentir impotencia y frustración frente a ello, pero con la rabia no llegaremos demasiado lejos. Nuestro trabajo ha de partir de la convicción de que la defensa del ambiente es un asunto de índole moral, de justicia: De no hacer a otros lo que no quiero que me hagan a mí. Ha terminado un año más en nuestras vidas, quizá el número de las victorias es muy bajo comparado con el de los fracasos, pero no tenemos tiempo de lamentarnos. No somos nosotros quienes nos rendimos ante las dificultades. Empieza el año 2017 y con él la ilusión y las ganas de seguir en esto. Se crearán nuevas organizaciones, otras se consolidarán más; surgirán activistas nuevos y mejor preparados. Un año más es una oportunidad para cambiar el mundo, para dejar de ser indiferentes y conformistas, para afirmarnos en aquello que creemos vale la pena mantener y ser mejores en lo que hacemos. Probablemente sea un exceso de optimismo confiar en que algún “Defensor del Ecosistema” vaya a intervenir desde los cielos para enderezar nuestros abusos ambientales. Es a nosotros a quienes corresponde hacerlo (esto es parte de la iniciativa del Poder de Uno). No tendría por qué ser imposible. Las aves (cuya inteligencia tendemos a subestimar), saben como mantener limpio su nido. Otro tanto puede decirse de los camarones, cuyo cerebro tiene el tamaño de una mota de polvo, y de las algas, y de los microorganismos unicelulares. Es tiempo de que también nosotros lo sepamos. Este año que inicia, continuaremos con nuestras acciones de protección del ambiente. Campañas cono #NoSeasPlástico seguirán presentes, igualmente seguiremos brindando los mejores consejos para combatir el calentamiento global, sin lugar a dudas uno de los mayores retos que ha enfrentado la humanidad a lo largo de su historia. Combatir el calentamiento global solo se logrará disminuyendo drásticamente el consumo de combustibles fósiles, por eso continuaremos luchando en contra de todo proyecto de extracción petrolera. Combatir la emisión de gases de efecto invernadero también incluye recomendar el abandono de carne, debido a las grandes cantidades de Metano que emite la ganadería a la atmosfera, más inclusive que los motores de combustión interna. Preserve Planet continuará participando activamente en la Comisión Interinstitucional que tiene a cargo la restauración del Parque Metropolitano La Sabana, uno de los pulmones más importantes de la ciudad de San José, en Costa Rica. Reforzaremos también la campaña contra el consumo de huevos de tortuga y la tenencia de vida silvestre. En las últimas semanas también nos incorporamos a una lucha de la sociedad civil, en donde vecinos del Este de la ciudad de San José, buscan detener la destrucción de casi cien árboles en terrenos de la Universidad de Costa Rica. Esperen noticias y mucha información por medio de nuestro sitio de Internet y también en nuestro perfil de Facebook. Muchas gracias a todas las personas que en los últimos años se han afiliado a esta organización y están trabajando todos los días, intensamente en la aplicación de El Poder de Uno. ¡Feliz año nuevo! Recuerden…somos parte del cambio. #elNuevoSerHumano

In [19]:
selected_data.iloc[0]['organizations']

['📃 Iniciamos 2017',
 'Comisión Interinstitucional',
 'Poder de Uno',
 'El Poder de Uno.']

# References
- [Intro to `spaCy`](https://spacy.io/usage/spacy-101/)
- [spaCy NER](https://spacy.io/usage/linguistic-features#named-entities)
- [spaCy visualizaition](https://spacy.io/usage/visualizers)

# FuzzyWuzzy

In [20]:
selected_data_aux = selected_data.copy()
selected_data_aux = selected_data_aux['Message']

In [21]:
selected_data_aux.shape

(62844,)

In [22]:
selected_data_aux.head()

0    FELIZ AÑO NUEVO! Belice, Costa Rica, El Salvad...
1    MENSAJE DE PRESERVE PLANET PARA EL NUEVO AÑO. ...
2    Un #FelizAño les desea el Instituto Distrital ...
3    Francia busca siempre "con el diálogo solucion...
4    FELIZ AÑO NUEVO! ⤵️ MENSAJE DE PRESERVE PLANET...
Name: Message, dtype: object

In [23]:
sin_duplicados = selected_data_aux.drop_duplicates()

In [24]:
sin_duplicados.shape

(58492,)

In [25]:
selected_data.columns

Index(['Message', 'Message_stpWrd', 'Message_clean_lemm_stpWrd',
       'organizations'],
      dtype='object')

In [26]:
selected_data.shape

(62844, 4)

Install ´rapidfuzz´ if necessarily

In [27]:
#!pip install rapidfuzz

In [28]:
from deduplication import remove_similar_messages_parallel, analyze_duplicates

In [29]:
#!pip install rapidfuzz

In [30]:
test_subset = selected_data.head(1000)
test_dedup = remove_similar_messages_parallel(test_subset)
analyze_duplicates(test_subset, test_dedup)

Pre-filtering messages...
Processing 574 groups using 15 processes...

Processing message groups: 100%|██████████| 574/574 [00:07<00:00, 74.54it/s]

Removed 100 similar messages.

Deduplication Analysis:
Original messages: 1,000
Unique messages: 900
Removed messages: 100
Reduction percentage: 10.00%

In [31]:
deduplicated_df = remove_similar_messages_parallel(selected_data)

# Analyze the results
analyze_duplicates(selected_data, deduplicated_df)

# save the deduplicated DataFrame
deduplicated_df.to_csv('deduplicated_2016.csv', index=False)

Pre-filtering messages...
Processing 575 groups using 15 processes...

Processing message groups: 100%|██████████| 575/575 [4:34:40<00:00, 28.66s/it]

Removed 5867 similar messages.

Deduplication Analysis:
Original messages: 62,844
Unique messages: 56,977
Removed messages: 5,867
Reduction percentage: 9.34%

In [32]:
print(selected_data["Message"].head(20))
print(deduplicated_df["Message"].head(20))

0     FELIZ AÑO NUEVO! Belice, Costa Rica, El Salvad...
1     MENSAJE DE PRESERVE PLANET PARA EL NUEVO AÑO. ...
2     Un #FelizAño les desea el Instituto Distrital ...
3     Francia busca siempre "con el diálogo solucion...
4     FELIZ AÑO NUEVO! ⤵️ MENSAJE DE PRESERVE PLANET...
5     El presidente francés, Francois Hollande, desa...
6     Con demasiado hielo en algunos lugares y e ins...
7     ¿Cómo hacer frente al calentamiento global sin...
8     FELIZ AÑO NUEVO! Barbados, Bolivia, Granada, G...
9     Campañas 🚩 Preserve Planet 🇨🇷 Costa Rica ➡️ Ex...
10    PRESERVE PLANET FELIZ AÑO NUEVO! Argentina, Su...
11    HITOS CLIMÁTICOS 2016 Despedimos el año con un...
12    #LOMÁSVISTO2016 Los pingüinos de la Antártida ...
13    chiste-grafico-calentamiento-global https://t....
14    Hollande lanza desafío a Trump en torno al cam...
15    InterCLIMA Arequipa fue esta vez sede de esta ...
16    Mandatario francés sostuvo que existe una “imp...
17    El calentamiento global para muchos es un mito...
18    Terminamos el 2016 con precipitaciones por enc...
19    Investigación 📖📚 Preserve Planet #AntesQueSeaT...
Name: Message, dtype: object
0     Un #FelizAño les desea el Instituto Distrital ...
1     Francia busca siempre "con el diálogo solucion...
2     El presidente francés, Francois Hollande, desa...
3     Con demasiado hielo en algunos lugares y e ins...
4     ¿Cómo hacer frente al calentamiento global sin...
5     Campañas 🚩 Preserve Planet 🇨🇷 Costa Rica ➡️ Ex...
6     HITOS CLIMÁTICOS 2016 Despedimos el año con un...
7     #LOMÁSVISTO2016 Los pingüinos de la Antártida ...
8     chiste-grafico-calentamiento-global https://t....
9     Hollande lanza desafío a Trump en torno al cam...
10    InterCLIMA Arequipa fue esta vez sede de esta ...
11    Mandatario francés sostuvo que existe una “imp...
12    El calentamiento global para muchos es un mito...
13    Terminamos el 2016 con precipitaciones por enc...
14    Hollande: París no permitirá que se cuestione ...
15    #ProyectosECOSUR El cambio climático implica e...
16    François Hollande, presidente de #Francia afir...
17                                        Sorprendente.
18    Para la ciudad más grande de EEUU, las verdade...
19    https://www.youtube.com/watch?v=_WwBPcI8eB0 ot...
Name: Message, dtype: object

In [33]:
# PRUEBA
test_data = pd.DataFrame({
    'Message': [
        "This is a test message",
        "This is a test message!", 
        "This is a completely different message",
        "This is a tst message",   
        "Hello world"
    ],
    'Message_stpWrd': ['dummy1', 'dummy2', 'dummy3', 'dummy4', 'dummy5'],
    'Message_clean_lemm_stpWrd': ['dummy1', 'dummy2', 'dummy3', 'dummy4', 'dummy5'],
    'organizations': ['org1', 'org2', 'org3', 'org4', 'org5']
})


deduplicated_df = remove_similar_messages_parallel(test_data)


print("\nOriginal DataFrame:")
print(test_data['Message'])
print("\nDeduplicated DataFrame:")
print(deduplicated_df['Message'])

Pre-filtering messages...
Processing 2 groups using 15 processes...

Processing message groups: 100%|██████████| 2/2 [00:03<00:00,  1.90s/it]

Removed 2 similar messages.

Original DataFrame:
0                    This is a test message
1                   This is a test message!
2    This is a completely different message
3                     This is a tst message
4                               Hello world
Name: Message, dtype: object

Deduplicated DataFrame:
0                   This is a test message!
1    This is a completely different message
2                               Hello world
Name: Message, dtype: object