# Load data

In [1]:
import pandas as pd

In [2]:
df = pd.read_pickle(r"..\..\..\data\preprocessed\clean_stemm_lemm_stop_words_uniques.pkl")

In [3]:
df.shape

(1097515, 17)

In [4]:
df.head()

,Facebook Id,Post Created,Total Interactions,Likes,Comments,Shares,Love,Wow,Haha,Sad,Angry,Care,Message,Message_stpWrd,Message_clean_stpWrd,Message_clean_stemm_stpWrd,Message_clean_lemm_stpWrd
0,153630631414604,2016-01-05 20:55:17 CST,"7,836",7266,442,63,51,1,9,2,0,2,A LOS NACIDOS ENTRE 1970 Y 1987 Somos una gene...,NACIDOS 1970 1987 generación especial denomina...,nacidos 1970 1987 generacion especial denomina...,nac 1970 1987 som gener especial denomin gener...,nacido 1970 1987 generacion especial denominar...
1,344760762323803,2018-03-25 20:22:33 CST,"12,530",2946,44,9025,357,4,112,7,17,18,PORQUE VOTARE POR GUSTAVO PETRO Hoy quiero com...,VOTARE GUSTAVO PETRO quiero compartir ustedes ...,votare gustavo petro quiero compartir ustedes ...,porqu votar gustav petr quier compart seguidor...,votare gustavo petro querer compartir seguidor...
2,663135523805166,2018-04-26 15:23:31 CDT,"3,727",2137,77,917,583,10,2,0,1,0,"Ministra de medio ambiente, a trabajar por el ...","Ministra medio ambiente, cambio climático desc...",ministra medio ambiente cambio climatico desca...,ministr medi ambient trabaj cambi climat desca...,ministra medio ambiente cambio climatico desca...
3,461295120574213,2016-05-02 17:59:04 CDT,"3,146",2548,249,188,123,7,28,2,1,0,A LOS NACIDOS ENTRE 1970 Y 1987 Somos una gene...,NACIDOS 1970 1987 generación especial denomina...,nacidos 1970 1987 generacion especial denomina...,nac 1970 1987 som gener especial denomin gener...,nacido 1970 1987 generacion especial denominar...
4,663135523805166,2016-06-28 23:41:26 CDT,"2,804",2367,57,181,87,5,3,8,96,0,AYÚDANOS A COMPARTIR LA IMAGEN.. Por tan magni...,AYÚDANOS COMPARTIR IMAGEN.. magnicfico POT (Pl...,ayudanos compartir imagen magnicfico pot plan ...,ayudan compart imag magnicf pot plan orden ter...,ayudano compartir imagen magnicfico pot plan o...

In [5]:
df.columns

Index(['Facebook Id', 'Post Created', 'Total Interactions', 'Likes',
       'Comments', 'Shares', 'Love', 'Wow', 'Haha', 'Sad', 'Angry', 'Care',
       'Message', 'Message_stpWrd', 'Message_clean_stpWrd',
       'Message_clean_stemm_stpWrd', 'Message_clean_lemm_stpWrd'],
      dtype='object')

In [6]:
selected_data = df[['Message' ,'Message_stpWrd', 'Message_clean_lemm_stpWrd']]

In [7]:
selected_data.head()

,Message,Message_stpWrd,Message_clean_lemm_stpWrd
0,A LOS NACIDOS ENTRE 1970 Y 1987 Somos una gene...,NACIDOS 1970 1987 generación especial denomina...,nacido 1970 1987 generacion especial denominar...
1,PORQUE VOTARE POR GUSTAVO PETRO Hoy quiero com...,VOTARE GUSTAVO PETRO quiero compartir ustedes ...,votare gustavo petro querer compartir seguidor...
2,"Ministra de medio ambiente, a trabajar por el ...","Ministra medio ambiente, cambio climático desc...",ministra medio ambiente cambio climatico desca...
3,A LOS NACIDOS ENTRE 1970 Y 1987 Somos una gene...,NACIDOS 1970 1987 generación especial denomina...,nacido 1970 1987 generacion especial denominar...
4,AYÚDANOS A COMPARTIR LA IMAGEN.. Por tan magni...,AYÚDANOS COMPARTIR IMAGEN.. magnicfico POT (Pl...,ayudano compartir imagen magnicfico pot plan o...

# spaCy

We are going to use `spaCy`'s pretrained models to extract all organizations mentioned on the posts

In [8]:
import spacy
from spacy import displacy
from collections import Counter

In [9]:
spacy.__version__

'3.7.4'

In [10]:
nlp = spacy.load('es_core_news_lg')

We will use `spaCy` models to identify and extract organizations from posts:

In [11]:
doc = nlp(selected_data.iloc[418233]['Message'])

In [12]:
displacy.serve(doc, style="ent")

c:\Users\eduardo.moreno\AppData\Local\anaconda3\envs\env_nlp\Lib\site-packages\spacy\displacy\__init__.py:106: UserWarning: [W011] It looks like you're calling displacy.serve from within a Jupyter notebook or a similar environment. This likely means you're already running a local web server, so there's no need to make displaCy start another one. Instead, you should be able to replace displacy.serve with displacy.render to show the visualization.
  warnings.warn(Warnings.W011)

Using the 'ent' visualizer
Serving on http://0.0.0.0:5000 ...

Shutting down server on port 5000.

In [13]:
doc.ents

(Día Mundial del Medio Ambiente,
 Ministerio de Defensa,
 República Dominicana,
 MIDE,
 Ministerio de Medio Ambiente y Recursos Naturales,
 Luchamos contra la tala de árboles para conservar las cuencas acuíferas,
 El Día Mundial del Medio Ambiente,
 Organización de Naciones Unidas,
 ONU)

Generar función para extraer todas las organizaciones mencionadas en cada un post de Facebook.

In [14]:
def get_orgs(text):
    doc = nlp(text)
    org_list = []
    for entity in doc.ents:
        if entity.label_ == 'ORG':
            org_list.append(entity.text)
    org_list = list(set(org_list))
    return org_list

The next cell takes around $4$ hours to extract all organizations...

In [15]:
if 1 == 0:
    selected_data['organizations'] = selected_data['Message'].apply(get_orgs)
    selected_data.to_pickle(r"..\..\..\data\preprocessed\full_data_organizations.pkl")
else:
    selected_data = pd.read_pickle(r"..\..\..\data\preprocessed\full_data_organizations.pkl")
selected_data.head()

,Message,Message_stpWrd,Message_clean_lemm_stpWrd,organizations
0,A LOS NACIDOS ENTRE 1970 Y 1987 Somos una gene...,NACIDOS 1970 1987 generación especial denomina...,nacido 1970 1987 generacion especial denominar...,"[Guns N'Roses, Coca-Cola, ThunderCats, Los Hal..."
1,PORQUE VOTARE POR GUSTAVO PETRO Hoy quiero com...,VOTARE GUSTAVO PETRO quiero compartir ustedes ...,votare gustavo petro querer compartir seguidor...,"[PETRO, PORQUE, GANA, POR]"
2,"Ministra de medio ambiente, a trabajar por el ...","Ministra medio ambiente, cambio climático desc...",ministra medio ambiente cambio climatico desca...,[]
3,A LOS NACIDOS ENTRE 1970 Y 1987 Somos una gene...,NACIDOS 1970 1987 generación especial denomina...,nacido 1970 1987 generacion especial denominar...,"[Guns N'Roses, Coca-Cola, ThunderCats, Los Hal..."
4,AYÚDANOS A COMPARTIR LA IMAGEN.. Por tan magni...,AYÚDANOS COMPARTIR IMAGEN.. magnicfico POT (Pl...,ayudano compartir imagen magnicfico pot plan o...,"[Oxford University, Centros, Harvard]"

Let's extract all organizations:

In [16]:
orgs = selected_data['organizations'].to_list()
orgs = [org for sublist in orgs for org in sublist]

In [17]:
org_freq = Counter(orgs)
org_freq.most_common(20)

[('Cambio Climático', 41057),
 ('ONU', 29559),
 ('Naciones Unidas', 10713),
 ('Gobierno', 7780),
 ('Unión Europea', 7550),
 ('IPCC', 5718),
 ('Congreso', 5680),
 ('UE', 5379),
 ('Acuerdo de París', 5350),
 ('NASA', 5298),
 ('FAO', 4736),
 ('WWF', 4566),
 ('Objetivos de Desarrollo Sostenible', 3880),
 ('OMS', 3801),
 ('Greenpeace', 3203),
 ('PNUD', 3082),
 ('Comisión de Medio Ambiente', 3074),
 ('UNAM', 3026),
 ('Senado', 2887),
 ('Organización de las Naciones Unidas', 2785)]

What about the following post?

In [18]:
print(selected_data.iloc[0]['Message'])

A LOS NACIDOS ENTRE 1970 Y 1987 Somos una generación especial y nos denominaron la generación X y como no, si nuestra infancia estuvo llena de cambios Somos la última generación que jugaba en la calle y en los recreos del colegio a las bolitas, a el escondite, somos la primera generación que jugó con videojuegos, fuimos a parques de atracciones y vimos caricaturas a color. Fuimos los últimos en grabar canciones de la radio en casettes (como olvidarlo si mientras se grababa en algunos casos no podíamos ni hablar) y vimos películas en versión Beta y VHS PERO orgullosos pioneros del personal stereo y los CD's. Cuantos no tuvimos que tragarnos, Salvado por la Campana (con todo y Screech), Beverly Hills 90210. Nosotros vimos la caída de torres gemelas y también vimos caer el muro de Berlín. Aprendimos a utilizar los ordenadores antes que nuestros padres y abuelos, y sobre todo antes de todos esos niños cerebritos de hoy en día y nunca vimos a los que no sabían usar los ordenadores como una especie de "retardados" como sucede hoy. Jugamos con el Double Dragon, Street Fighter, empezamos el Mortal Kombat, el tetris, el Mario Bross, nos pegábamos a la tele a mirar Hugo y como otros jugaban desde sus casas usando el teléfono de red fija!! vimos los anuncios de los primeros celulares (que parecían ladrillos) y creímos que Internet sería un mundo libre. Somos la Generación de Xuxa, Robotech, Gi Joe, Los Halcones Galácticos, los ThunderCats, los Transformers, He-Man y las Tortugas Ninja, Del Correcaminos, Los Supercampeones, Espartaco, Mazinger, de los Pitufos, La Pantera Rosa, Los Picapiedras, El pájaro loco, Candi Candi, Remi y Marco. Los que crecieron escuchando a Madonna, Michael Jackson y Guns N'Roses, New Kids on the block, Por supuesto en ver y vivir los primeros VIDEOS MUSICALES , Los Locomía y sus abanicos. La última generación de las botellas de litro de Coca-Cola familiar cuando un litro alcanzaba para toda la familia!! Y los últimos en ser mandados a comprar en la bolsa de cuadritos. Este correo está dedicado a las personas que nacieron entre 1970 y 1987. La verdad es que no sé cómo hemos sobrevivido!!!! Mirando atrás es difícil creer que estemos vivos: viajábamos en autos sin cinturones de seguridad traseros, sin sillitas especiales y sin air-bag, hacíamos viajes de 10-12h y no sufríamos el síndrome de la clase turista. No tuvimos puertas con protecciones, armarios o frascos de medicinas con tapa a prueba de niños. Andábamos en bicicleta o patines sin casco, ni protectores para rodillas y codos. Los columpios eran de metal y resbaladilla y con esquinas en punta oxidada . No había celulares!!!!. Íbamos a clase cargados de libros y cuadernos, todo metido en una mochila o bolsón que rara vez tenía refuerzo para los hombros y mucho menos, ruedas!! Cuantos no recogimos del suelo nuestros útiles al romperse la mochila! Y el que tenia un pantalón marca Wrangler. No tuvimos PlayStation, no había 99 canales de televisión, pantallas planas, sonido surround, mp3s, ipods, computadores e Internet, pero nos lo pasábamos de lo lindo tirándonos globos con agua, o jugando con los playmobil. Y nunca escuchamos sobre el calentamiento global. No era necesario tener fotoblog, Hi5 o MySpace, Facebook, twitter, para saber si existíamos, bastaba con hacer bien fuerte la "silvada" del grupo o gritar fuera de la casa, en plena calle, para que toda la cuadra saliera de sus casas. Éramos el zanahoria, la china, la flaca, la pecosa, el negro, el chato o cosas así, pero todos pertenecíamos al mismo grupo y por el apodo sabíamos de inmediato quien era (ahora serian zanahoriitax, shiina, flahkah, p'kosiita, neghhro y shatto). jjajajaja Éramos responsables de nuestras acciones y acarreábamos con las consecuencias, no había nadie para resolver eso. Tuvimos libertad, fracaso, éxito y responsabilidad, y aprendimos a crecer con todo ello. ¡FELICIDADES! Sobrevivimos a un mega cambio, ahora si tienes hijos, piensa por que no lo dejas hacer esas cosas si lo pasaste tan bien? Pasa esto a otros que tuvieron la suerte de crecer como niños, recordemos lo bueno de la vida. Lo fácil que es ser felices, la grandeza de lo sencillo. No necesitamos todas esas etiquetas, todas esas superficialidades, cosas, móviles, ropa... recordemos cómo ser niños, pero sobre todo, cómo ser libres!! Por: Luis Sosa

In [19]:
selected_data.iloc[0]['organizations']

["Guns N'Roses",
 'Coca-Cola',
 'ThunderCats',
 'Los Halcones Galácticos',
 'Robotech']

# References
- [Intro to `spaCy`](https://spacy.io/usage/spacy-101/)
- [spaCy NER](https://spacy.io/usage/linguistic-features#named-entities)
- [spaCy visualizaition](https://spacy.io/usage/visualizers)